// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NationStatesAPIBot;

namespace NationStatesAPIBot.Migrations
{
    [DbContext(typeof(BotDbContext))]
    partial class BotDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028");

            modelBuilder.Entity("NationStatesAPIBot.Entities.Nation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int>("StatusId");

                    b.Property<DateTime>("StatusTime");

                    b.HasKey("Id");

                    b.HasIndex("StatusId");

                    b.ToTable("Nations");
                });

            modelBuilder.Entity("NationStatesAPIBot.Entities.NationStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("NationStatuses");
                });

            modelBuilder.Entity("NationStatesAPIBot.Entities.Nation", b =>
                {
                    b.HasOne("NationStatesAPIBot.Entities.NationStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
